// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../database/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2675847420505076543),
      name: 'BlockVector',
      lastPropertyId: const obx_int.IdUid(3, 6007357884080982916),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6328327352204386913),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8544314459225515504),
            name: 'documentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 6853578938301794265),
            relationTarget: 'DreamkeeperDocument'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6007357884080982916),
            name: 'blockId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 7869460569440935827),
            relationTarget: 'DocumentBlock')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1904111289124073799),
      name: 'DocumentBlock',
      lastPropertyId: const obx_int.IdUid(5, 1863663107051040057),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6965360099172755903),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 699639639355947395),
            name: 'blockNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6500228856623463333),
            name: 'plaintext',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4093164196411766370),
            name: 'documentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 7118222247900652012),
            relationTarget: 'DreamkeeperDocument'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1863663107051040057),
            name: 'embeddingId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 2768205539878833320),
            relationTarget: 'BlockVector')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5072485273022926526),
      name: 'DreamkeeperDocument',
      lastPropertyId: const obx_int.IdUid(4, 3074566525603366904),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5324606972050200035),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4592375958659850233),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4472523615307382233),
            name: 'createdOn',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3074566525603366904),
            name: 'editedOn',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'entries', srcEntity: 'FeedEntry', srcField: 'document'),
        obx_int.ModelBacklink(
            name: 'blocks', srcEntity: 'DocumentBlock', srcField: 'document')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 9222437547379108457),
      name: 'Feed',
      lastPropertyId: const obx_int.IdUid(4, 5838987186544833151),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3675839831431150906),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5174166070797647372),
            name: 'title',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(5, 4731260858194973115)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8946571422089713458),
            name: 'deletable',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5838987186544833151),
            name: 'lastViewed',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'entries', srcEntity: 'FeedEntry', srcField: 'feed')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 2447803695644195486),
      name: 'FeedEntry',
      lastPropertyId: const obx_int.IdUid(5, 6633187234008207953),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3251026472852682301),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 474926429931660973),
            name: 'dateRecommendedToUser',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5943826710688967312),
            name: 'dateBlacklistedByUser',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8664219073481760629),
            name: 'feedId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 155353596200286940),
            relationTarget: 'Feed'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6633187234008207953),
            name: 'documentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 7499596532061033826),
            relationTarget: 'DreamkeeperDocument')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 2447803695644195486),
      lastIndexId: const obx_int.IdUid(7, 7499596532061033826),
      lastRelationId: const obx_int.IdUid(3, 8151844155431242869),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [
        3383744319323622071,
        7059936845439524170,
        8151844155431242869
      ],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    BlockVector: obx_int.EntityDefinition<BlockVector>(
        model: _entities[0],
        toOneRelations: (BlockVector object) => [object.document, object.block],
        toManyRelations: (BlockVector object) => {},
        getId: (BlockVector object) => object.id,
        setId: (BlockVector object, int id) {
          object.id = id;
        },
        objectToFB: (BlockVector object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.document.targetId);
          fbb.addInt64(2, object.block.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = BlockVector(id: idParam);
          object.document.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.document.attach(store);
          object.block.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.block.attach(store);
          return object;
        }),
    DocumentBlock: obx_int.EntityDefinition<DocumentBlock>(
        model: _entities[1],
        toOneRelations: (DocumentBlock object) =>
            [object.document, object.embedding],
        toManyRelations: (DocumentBlock object) => {},
        getId: (DocumentBlock object) => object.id,
        setId: (DocumentBlock object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentBlock object, fb.Builder fbb) {
          final plaintextOffset = fbb.writeString(object.plaintext);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.blockNumber);
          fbb.addOffset(2, plaintextOffset);
          fbb.addInt64(3, object.document.targetId);
          fbb.addInt64(4, object.embedding.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final blockNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final plaintextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object =
              DocumentBlock(blockNumberParam, plaintextParam, id: idParam);
          object.document.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.document.attach(store);
          object.embedding.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.embedding.attach(store);
          return object;
        }),
    DreamkeeperDocument: obx_int.EntityDefinition<DreamkeeperDocument>(
        model: _entities[2],
        toOneRelations: (DreamkeeperDocument object) => [],
        toManyRelations: (DreamkeeperDocument object) => {
              obx_int.RelInfo<FeedEntry>.toOneBacklink(5, object.id,
                  (FeedEntry srcObject) => srcObject.document): object.entries,
              obx_int.RelInfo<DocumentBlock>.toOneBacklink(4, object.id,
                      (DocumentBlock srcObject) => srcObject.document):
                  object.blocks
            },
        getId: (DreamkeeperDocument object) => object.id,
        setId: (DreamkeeperDocument object, int id) {
          object.id = id;
        },
        objectToFB: (DreamkeeperDocument object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contentOffset);
          fbb.addInt64(2, object.createdOn.millisecondsSinceEpoch);
          fbb.addInt64(3, object.editedOn.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final createdOnParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final editedOnParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final object = DreamkeeperDocument(contentParam,
              id: idParam, createdOn: createdOnParam, editedOn: editedOnParam);
          obx_int.InternalToManyAccess.setRelInfo<DreamkeeperDocument>(
              object.entries,
              store,
              obx_int.RelInfo<FeedEntry>.toOneBacklink(
                  5, object.id, (FeedEntry srcObject) => srcObject.document));
          obx_int.InternalToManyAccess.setRelInfo<DreamkeeperDocument>(
              object.blocks,
              store,
              obx_int.RelInfo<DocumentBlock>.toOneBacklink(4, object.id,
                  (DocumentBlock srcObject) => srcObject.document));
          return object;
        }),
    Feed: obx_int.EntityDefinition<Feed>(
        model: _entities[3],
        toOneRelations: (Feed object) => [],
        toManyRelations: (Feed object) => {
              obx_int.RelInfo<FeedEntry>.toOneBacklink(
                      4, object.id, (FeedEntry srcObject) => srcObject.feed):
                  object.entries
            },
        getId: (Feed object) => object.id,
        setId: (Feed object, int id) {
          object.id = id;
        },
        objectToFB: (Feed object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addBool(2, object.deletable);
          fbb.addInt64(3, object.lastViewed?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastViewedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final deletableParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final lastViewedParam = lastViewedValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastViewedValue);
          final object = Feed(titleParam,
              id: idParam,
              deletable: deletableParam,
              lastViewed: lastViewedParam);
          obx_int.InternalToManyAccess.setRelInfo<Feed>(
              object.entries,
              store,
              obx_int.RelInfo<FeedEntry>.toOneBacklink(
                  4, object.id, (FeedEntry srcObject) => srcObject.feed));
          return object;
        }),
    FeedEntry: obx_int.EntityDefinition<FeedEntry>(
        model: _entities[4],
        toOneRelations: (FeedEntry object) => [object.feed, object.document],
        toManyRelations: (FeedEntry object) => {},
        getId: (FeedEntry object) => object.id,
        setId: (FeedEntry object, int id) {
          object.id = id;
        },
        objectToFB: (FeedEntry object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dateRecommendedToUser?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.dateBlacklistedByUser?.millisecondsSinceEpoch);
          fbb.addInt64(3, object.feed.targetId);
          fbb.addInt64(4, object.document.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateRecommendedToUserValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final dateBlacklistedByUserValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateRecommendedToUserParam = dateRecommendedToUserValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateRecommendedToUserValue);
          final dateBlacklistedByUserParam = dateBlacklistedByUserValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateBlacklistedByUserValue);
          final object = FeedEntry(
              id: idParam,
              dateRecommendedToUser: dateRecommendedToUserParam,
              dateBlacklistedByUser: dateBlacklistedByUserParam);
          object.feed.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.feed.attach(store);
          object.document.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.document.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BlockVector] entity fields to define ObjectBox queries.
class BlockVector_ {
  /// See [BlockVector.id].
  static final id =
      obx.QueryIntegerProperty<BlockVector>(_entities[0].properties[0]);

  /// See [BlockVector.document].
  static final document =
      obx.QueryRelationToOne<BlockVector, DreamkeeperDocument>(
          _entities[0].properties[1]);

  /// See [BlockVector.block].
  static final block = obx.QueryRelationToOne<BlockVector, DocumentBlock>(
      _entities[0].properties[2]);
}

/// [DocumentBlock] entity fields to define ObjectBox queries.
class DocumentBlock_ {
  /// See [DocumentBlock.id].
  static final id =
      obx.QueryIntegerProperty<DocumentBlock>(_entities[1].properties[0]);

  /// See [DocumentBlock.blockNumber].
  static final blockNumber =
      obx.QueryIntegerProperty<DocumentBlock>(_entities[1].properties[1]);

  /// See [DocumentBlock.plaintext].
  static final plaintext =
      obx.QueryStringProperty<DocumentBlock>(_entities[1].properties[2]);

  /// See [DocumentBlock.document].
  static final document =
      obx.QueryRelationToOne<DocumentBlock, DreamkeeperDocument>(
          _entities[1].properties[3]);

  /// See [DocumentBlock.embedding].
  static final embedding = obx.QueryRelationToOne<DocumentBlock, BlockVector>(
      _entities[1].properties[4]);
}

/// [DreamkeeperDocument] entity fields to define ObjectBox queries.
class DreamkeeperDocument_ {
  /// See [DreamkeeperDocument.id].
  static final id =
      obx.QueryIntegerProperty<DreamkeeperDocument>(_entities[2].properties[0]);

  /// See [DreamkeeperDocument.content].
  static final content =
      obx.QueryStringProperty<DreamkeeperDocument>(_entities[2].properties[1]);

  /// See [DreamkeeperDocument.createdOn].
  static final createdOn =
      obx.QueryDateProperty<DreamkeeperDocument>(_entities[2].properties[2]);

  /// See [DreamkeeperDocument.editedOn].
  static final editedOn =
      obx.QueryDateProperty<DreamkeeperDocument>(_entities[2].properties[3]);

  /// see [DreamkeeperDocument.entries]
  static final entries =
      obx.QueryBacklinkToMany<FeedEntry, DreamkeeperDocument>(
          FeedEntry_.document);

  /// see [DreamkeeperDocument.blocks]
  static final blocks =
      obx.QueryBacklinkToMany<DocumentBlock, DreamkeeperDocument>(
          DocumentBlock_.document);
}

/// [Feed] entity fields to define ObjectBox queries.
class Feed_ {
  /// See [Feed.id].
  static final id = obx.QueryIntegerProperty<Feed>(_entities[3].properties[0]);

  /// See [Feed.title].
  static final title =
      obx.QueryStringProperty<Feed>(_entities[3].properties[1]);

  /// See [Feed.deletable].
  static final deletable =
      obx.QueryBooleanProperty<Feed>(_entities[3].properties[2]);

  /// See [Feed.lastViewed].
  static final lastViewed =
      obx.QueryDateProperty<Feed>(_entities[3].properties[3]);

  /// see [Feed.entries]
  static final entries =
      obx.QueryBacklinkToMany<FeedEntry, Feed>(FeedEntry_.feed);
}

/// [FeedEntry] entity fields to define ObjectBox queries.
class FeedEntry_ {
  /// See [FeedEntry.id].
  static final id =
      obx.QueryIntegerProperty<FeedEntry>(_entities[4].properties[0]);

  /// See [FeedEntry.dateRecommendedToUser].
  static final dateRecommendedToUser =
      obx.QueryDateProperty<FeedEntry>(_entities[4].properties[1]);

  /// See [FeedEntry.dateBlacklistedByUser].
  static final dateBlacklistedByUser =
      obx.QueryDateProperty<FeedEntry>(_entities[4].properties[2]);

  /// See [FeedEntry.feed].
  static final feed =
      obx.QueryRelationToOne<FeedEntry, Feed>(_entities[4].properties[3]);

  /// See [FeedEntry.document].
  static final document =
      obx.QueryRelationToOne<FeedEntry, DreamkeeperDocument>(
          _entities[4].properties[4]);
}
